apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret  # Specify a valid name for your Secret
  labels:
    name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==   
  rmq-pass: Z3Vlc3Q=
